version: '3'

tasks:
  apply:
    cmds:
      - task: apply-system
      - task: apply-users


  apply-system:
    cmds:
      - doas nixos-rebuild --flake .#nixos switch


  flash-os:
    cmds:
      - doas nixos-rebuild --flake .#flash-os switch



  apply-users:
    cmds:
      - nix build .#homeManagerConfigurations.glenda.activationPackage
      - ./result/activate

  update-system:
    cmds:
      - nix flake update

  auto-snapshot:
    cmds:
      - doas zfs set com.sun:auto-snapshot=true NIXROOT/home

  cp-hardware:
    cmds:
      - cp -f /etc/nixos/hardware-configuration.nix system
