version: '3'

tasks:
  new-system:
    cmds:
      - task: cp-hardware
      - task: apply

  apply:
    cmds:
      - task: hostid
      - task: apply-system
      - task: apply-users
      - task: rm-hostid

  apply-system:
    cmds:
      - doas nixos-rebuild --flake .#nixos -p nixconf switch

  hostid:
    cmds:
      - sed -i "s/<hostId>/$(head -c 8 /etc/machine-id)/g" system/configuration.nix
  
  rm-hostid:
    cmds:
      - sed -i "s/$(head -c 8 /etc/machine-id)/<hostId>/g" system/configuration.nix
 
  flash-os:
    cmds:
      - doas nixos-rebuild --flake .#flash-os -p flash-os switch
  server:
    cmds:
      - doas nixos-rebuild --flake .#server -p server switch

  apply-users:
    cmds:
      - nix build .#homeManagerConfigurations.glenda.activationPackage
      - ./result/activate

  update-system:
    cmds:
      - nix flake update

  auto-snapshot:
    cmds:
      - doas zfs set com.sun:auto-snapshot=true NIXROOT/home

  cp-hardware:
    cmds:
      - cp -f /etc/nixos/hardware-configuration.nix system

  update:
    cmds:
      - nix flake update
  
  cupdate:
    cmds:
      - task: update
      - git add flake.lock
      - git commit -m "update"

  iso:
    cmds:
      - nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=system/iso.nix

  flash-os-iso:
    cmds:
      - nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=system/flash-os/iso.nix


  pull:
    cmds:
      - git pull

  push:
    cmds:
      - task: apply
      - git push
  jellyfin:
    cmds:
      - doas mkdir /jellyfin
      - doas chown -R jellyfin:jellyfin /jellyfin
