version: '3'

tasks:
  iso:
    cmds:
      - nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix

  flash-os:
    cmds:
      - nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.flash-os.nix

