on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz"
      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: gvolpe-nixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"  

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix

      - name: Flake
        run: nix flake check
